KestrelSettings:
  Listens:
    127.0.0.1:
      - 5000
      - 5001
  UnixSocketPath:
    - "/tmp/danmu.sock"

WithOrigins:
  - "*"

LiveWithOrigins:
  - "http://localhost"
  - "http://localhost:4000"
  - "https://doc.video.xwhite.studio"

UseHttps:
  UseHttpsRedirection: false
  UseHsts: false

DanmuSql:
  Directory: "./DataBase/"

BiliBiliSetting:
  Cookie: ""
  CidCacheTime: 72
  DanmuCacheTime: 5

EasyCaching:
  InMemory:
    MaxRdSecond: 60
    EnableLogging: false
    LockMs: 5000
    SleepMs: 300
    DBConfig:
      SizeLimit: 10000
      ExpirationScanFrequency: 60
      EnableReadDeepClone: true
      EnableWriteDeepClone: false
